services:
    blogger.symblog.admin.sites:
        class: Robot\ParserBundle\Admin\ParsersAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Parser, label: Parser }
        arguments:
            - null
            - Robot\ParserBundle\Entity\ParserBilstein
            - RobotParserBundle:ParsersAdmin
