services:

    blogger.symblog.admin.parsers:
        class: Robot\ParserBundle\Admin\ParsersAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Parsers, label: Parsers }
        arguments:
            - null
            - Robot\ParserBundle\Entity\Parsers
            - RobotParserBundle:ParsersAdmin
    blogger.symblog.admin.items:
        class: Robot\ParserBundle\Admin\ItemsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Items, label: Items }
        arguments:
            - null
            - Robot\ParserBundle\Entity\Items
            - RobotParserBundle:ItemsAdmin
    parsers.service:
        class: Robot\ParserBundle\Model\Parsers
        arguments: [ @doctrine.orm.entity_manager ]